runtime: python39

entrypoint: gunicorn backend.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  SECRET_KEY: "h#+*60&=c367+wld86!3+5h4qm_=-etpq$7q_e#gi)*+ce6l!t"
  DEBUG: "False"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
