runtime: python310  # ✅ Use python310 instead of python39 (recommended by Google)
entrypoint: gunicorn backend.wsgi --bind :$PORT

env_variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  SECRET_KEY: "django-insecure-ur44l-f$-ra2)_(a9!570i1oh3a012#0h123lm4caq!1_1d#^j"
  DEBUG: "False"

  # ✅ Environment variables for database
  DB_NAME: "smartlight_data"
  DB_USER: "postgres"
  DB_PASSWORD: "9185"
  DB_HOST: "34.59.166.106"
  DB_PORT: "5432"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
